### ISSUE TITLE
Desync with compost

### ISSUE THREAD

**Issue by vladimirbrenek** [juanosarg/VanillaPlantsExpanded#1]
Hello,

we are playing with friends almost whole Vanilla expanded. Unfortunately, we are not able to use farming soil, which is causing a desync.

How:
When compost in Wooden Box is completed, it drops fertilizer and in the next second, it makes desync. Don't know if it's happening also with the barrel.

Mod list:
<ModsConfigData>
  <version>1.2.2900 rev837</version>
  <activeMods>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>rwmt.multiplayer</li>
    <li>rwmt.multiplayercompatibility</li>
    <li>unlimitedhugs.hugslib</li>
    <li>brrainz.rangefinder</li>
    <li>zyxabacab.nosympathyforprisoners</li>
    <li>gguake.ui.simplesearchbar</li>
    <li>codeoptimist.jobsofopportunity</li>
    <li>weilbyte.snapout</li>
    <li>caesarv6.damageindicators</li>
    <li>targhetti.showdrafteesweapon</li>
    <li>erdelf.humanoidalienraces</li>
    <li>hatti.qualitybuilder</li>
    <li>porquenolosdos.colorcodedmoodbar</li>
    <li>orion.hospitality</li>
    <li>neceros.reinforcedwalls</li>
    <li>brrainz.cameraplus</li>
    <li>jaxxa.ed.embrasures</li>
    <li>edb.preparecarefully</li>
    <li>avilmask.commonsense</li>
    <li>pinochemicali.moretradeships</li>
    <li>zylle.morevanillabiomes</li>
    <li>notfood.researchpal</li>
    <li>jaxe.rimhud</li>
    <li>linkolas.stabilize</li>
    <li>crlsniper.realisticrooms</li>
    <li>frozensnowfox.filthvanisheswithrainandtime</li>
    <li>murmur.walllight</li>
    <li>oskarpotocki.vanillafactionsexpanded.core</li>
    <li>haplo.miscellaneous.robots</li>
    <li>vanillaexpanded.vaeas</li>
    <li>vanillaexpanded.vaeau</li>
    <li>vanillaexpanded.vaebf</li>
    <li>vanillaexpanded.vaecd</li>
    <li>vanillaexpanded.vaed</li>
    <li>vanillaexpanded.vaeed</li>
    <li>vanillaexpanded.vaeis</li>
    <li>vanillaexpanded.vaetf</li>
    <li>vanillaexpanded.vaetr</li>
    <li>vanillaexpanded.vaets</li>
    <li>vanillaexpanded.vaet</li>
    <li>vanillaexpanded.vappe</li>
    <li>vanillaexpanded.varme</li>
    <li>vanillaexpanded.vbrewe</li>
    <li>vanillaexpanded.vbrewecandt</li>
    <li>oskarpotocki.vfe.insectoid</li>
    <li>vanillaexpanded.vcooke</li>
    <li>vanillaexpanded.vcookestews</li>
    <li>vanillaexpanded.vbookse</li>
    <li>vse.perrypersistent</li>
    <li>vanillaexpanded.vweg</li>
    <li>vanillaexpanded.vwe</li>
    <li>vanillaexpanded.vweq</li>
    <li>vanillaexpanded.vtexe</li>
    <li>vse.igorinvader</li>
    <li>vse.freyafierce</li>
    <li>vse.empressevil</li>
    <li>vanillaexpanded.vplantsesucculents</li>
    <li>vanillaexpanded.vplantse</li>
    <li>vanillaexpanded.vfespacer</li>
    <li>vanillaexpanded.vfepropsanddecor</li>
    <li>vanillaexpanded.vfeproduction</li>
    <li>oskarpotocki.vanillafactionsexpanded.medievalmodule</li>
    <li>vanillaexpanded.vwel</li>
    <li>vanillaexpanded.vhe.beards</li>
    <li>oskarpotocki.vanillafactionsexpanded.settlersmodule</li>
    <li>oskarpotocki.vfe.vikings</li>
    <li>vanillaexpanded.vhe</li>
    <li>co.uk.epicguru.bettertranshumanists</li>
    <li>vanillaexpanded.vfesecurity</li>
    <li>meltup.beautifuloutdoors</li>
    <li>mlie.cannibalmeals</li>
    <li>neceros.balancedeclipseandsolarflare</li>
    <li>neceros.badcanbegood</li>
    <li>vanillaexpanded.vfefarming</li>
    <li>revolus.animalsarefun</li>
    <li>syrchalis.doormats</li>
    <li>kapitanoczywisty.changemapedge</li>
    <li>goudaquiche.ltfmantisrace</li>
    <li>ratys.madskills</li>
    <li>catachat.inspirationtweaks</li>
    <li>nunahuralshamikh.medmed</li>
    <li>sharpedo.kenshiapparel</li>
    <li>elkyelky.houseplants</li>
    <li>herdmigration.velcroboy333</li>
    <li>syrchalis.harvestyieldpatch</li>
    <li>daniledman.hardworkinganimals</li>
    <li>sarg.geneticrim</li>
    <li>automatic.gunplay</li>
    <li>kittahkhan.grazeup</li>
    <li>jamaicancastle.rf.fertilefields</li>
    <li>roolo.dualwield</li>
    <li>dubwise.dubsskylights</li>
    <li>dubwise.dubspaintshop</li>
    <li>bob.draggablecornerss</li>
    <li>tikubonn.dontblockdoor</li>
    <li>petetimessix.compacthediffs</li>
    <li>vanillaexpanded.vfemedical</li>
    <li>smashphil.carrycapacityfixed</li>
    <li>daniledman.combatupdate</li>
    <li>sarg.alphaanimals</li>
    <li>gewen.additionaltraits</li>
    <li>spoonshortage.adogsaidanimalprosthetics</li>
    <li>uuugggg.replacestuff</li>
    <li>halo.rsf</li>
    <li>grimm.unlimited</li>
    <li>sig.mantodeanrace</li>
    <li>com.yayo.combat3</li>
    <li>murmur.subsurfaceconduit</li>
    <li>pinochemicali.skilledstonecutting</li>
    <li>showhair.kv.rw</li>
    <li>petetimessix.simplesidearms</li>
    <li>roolo.runandgun</li>
    <li>rimfridge.kv.rw</li>
    <li>machine.rtr</li>
    <li>sgc.quests</li>
    <li>milk.poleepkwaupdate</li>
    <li>murmur.pawnnamevariety</li>
    <li>sdknm2.qualityofbuilding</li>
    <li>hobtook.mortaraccuracy</li>
    <li>frozensnowfox.morequests</li>
    <li>ogre.ogrestack</li>
    <li>moretraitslots.kv.rw</li>
    <li>spino.megafauna</li>
    <li>kyd.prosthetics</li>
    <li>notfood.mendandrecycle</li>
    <li>leion247658.miscvhcraftablehrobots</li>
    <li>neceros.metaldontburn</li>
    <li>vanillaexpanded.vfeart</li>
    <li>vanillaexpanded.vfecore</li>
    <li>sarg.geneticrimmegafauna</li>
    <li>lwm.deepstorage</li>
    <li>alaestor.miscrobots.plusplus</li>
    <li>fluffy.modmanager</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
  </knownExpansions>
</ModsConfigData>

**Comment by juanosarg** [comment]
This mod doesn't add compost, fertilizer or a wooden box

**Comment by vladimirbrenek** [comment]
I am sorry, I found the mod making this problem
